#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times.

IP_ADDRESS=$1

if [ $# -eq 1 ]; then
  ping -c5 "$IP_ADDRESS"
else
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
