#!/usr/bin/env bash

### BEGIN INIT INFO
# Provides:         manages `manage_my_process`
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:
# Description:
### END INIT INFO

start_process() {
	# Run script in background
	./manage_my_process &
	# Create a file containing PID of the process
	echo "$!" > /var/run/my_process.pid

	echo "manage_my_process started"
}

stop_process() {
	# Read PID from file
	pid=$(cat /var/run/my_process.pid)
	# Stop process using the PID and delete PID file
	kill "$pid" && rm /var/run/my_process.pid

	echo "manage_my_process stopped"
}

restart_process() {
	# Stop and start the manage_my_process script
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid

	echo "manage_my_process restarted"
}

# Check argument passed to the script
case "$1" in
	start)
		start_process
		;;
	stop)
		stop_process
		;;
	restart)
		restart_process
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
